version: '3'
services:
  subsync:
    build: .
    container_name: subsyncforge
    volumes:
      - ./output:/app/output
      - ./data:/app/data
      - ./.git:/app/.git
      - ../cores:/app/.cores
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "23000:3000"
    network_mode: bridge
