version: '3'
services:
  subsync:
    build: .
    container_name: subsyncforge
    volumes:
      - ./output:/app/output
      - ./data:/app/data
      - ./.git:/app/.git
      - ../cores:/app/.cores
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "23000:3000"
    networks:
      - subsync-net

  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    restart: always
    ports:
      - "25500:25500"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - subsync-net

networks:
  subsync-net:
    driver: bridge
