# SubSyncForge 自定义节点配置
# 此文件用于配置订阅源和输出格式

# 订阅源配置 - 所有订阅将被合并
subscriptions:
  # 订阅源列表

  - name: "cmm"
    url: "https://subcheck.fiz.dpdns.org/download/sub"
    enabled: true 

  - name: "ppua"
    url: "https://sub-store.isfree.pp.ua/download/sub?target=URI"
    enabled: true 

  - name: "loc"
    url: "https://kkb.9901158.xyz/loc.yaml"
    enabled: true
  
  - name: "alalbb"
    url: "https://c.alalbb.top/clash"
    enabled: true
  
  - name: "zu"
    url: "https://hssq.cc/5dccpz"
    enabled: true
  
  - name: "ss"
    url: "https://mxlsub.me/newfull"
    enabled: true
    
# 输出配置
output:
  # 是否将节点去重
  deduplication: true
  
  # 输出目录
  dir: "output"
  
  # 数据存储目录
  data_dir: "data"
  
  # 生成的配置文件
  configs:
    # Mihomo (Clash Meta) 配置
    - name: "mihomo"
      template: "templates/mihomo.yaml"
      path: "mihomo.yaml"
      enabled: true
    
    # Surge 配置
    - name: "surge"
      template: "templates/surge.conf"
      path: "surge.conf"
      enabled: true
    
    # Sing-box 配置
    - name: "singbox"
      template: "templates/singbox.json"
      path: "singbox.json"
      enabled: true
    
    # V2Ray 配置 (选择第一个节点作为默认)
    - name: "v2ray"
      template: "templates/v2ray.json"
      path: "v2ray.json"
      enabled: true
      options:
        use_first_node: true

# 测试配置
testing:
  # 是否启用节点测试
  enabled: true
  
  # 测试并发数（同时测试多少个节点）
  concurrency: 5
  
  # 测试超时时间（毫秒）
  timeout: 5000
  
  # 测试URL
  test_url: "http://www.google.com/generate_204"
  
  # 是否只保留测试成功的节点
  filter_invalid: true
  
  # 按延迟排序
  sort_by_latency: true
  
  # 保留延迟低于此值的节点（毫秒，0表示不限制）
  max_latency: 1500
  
  # 保留最大节点数量（0表示不限制）
  max_nodes: 0
  
  # 是否验证并更正节点地区信息
  verify_location: true
  
  # IP地址定位相关配置
  ip_location:
    # 定位服务API URL (使用{ip}作为占位符)
    api_url: "https://ipinfo.io/{ip}/json"
    # API密钥 (可选)
    api_key: ""
    # 缓存时间(毫秒), 默认7天
    cache_time: 604800000

# 高级设置
advanced:
  # 缓存过期时间（秒）
  cache_ttl: 3600
  
  # 日志级别: debug, info, warn, error
  log_level: "info"
  
  # 使用代理获取订阅内容
  proxy_for_subscription: false
  
  # 节点排序
  sort_nodes: true
  
  # 定时同步设置（分钟）
  sync_interval: 360

# 计划任务
schedule:
  # 是否启用计划任务
  enabled: true
  
  # 同步订阅任务 - 每6小时执行一次
  sync_subscription:
    cron: "0 */6 * * *"  # 每6小时执行一次 (0分, 每6小时, 每天, 每月, 每周)
    enabled: true
    command: "npm run sync"
    
  # 清理缓存任务 - 每周执行一次
  clean_cache:
    cron: "0 0 * * 0"  # 每周日凌晨执行一次 (0分, 0时, 每天, 每月, 周日)
    enabled: true
    command: "node src/scripts/clean-cache.js"
