name: Sync Subscriptions

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:        # 支持手动触发
  
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # 显式授予写入权限
    # 添加超时限制，设置为5小时30分钟，留出一些余量
    timeout-minutes: 330
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # 获取完整历史记录
      
      # 先设置pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      
      # 然后设置Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'    # 启用Node模块缓存
      
      # 添加缓存恢复步骤
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      
      # 添加数据目录缓存，支持增量处理
      - name: Cache subscription data
        uses: actions/cache@v3
        with:
          path: data
          key: ${{ runner.os }}-subscription-data-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-subscription-data-
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build project
        run: pnpm build
      
      - name: Run sync script
        run: node dist/scripts/sync-subscriptions.js
        env:
          BARK_URL: ${{ secrets.BARK_URL }}
          BARK_TITLE: SubSyncForge
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 添加所有更改
          git add -A
          
          # 检查是否有变更
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # 提交更改
          git commit -m "Update subscriptions: $(date +'%Y-%m-%d %H:%M:%S')"
          
          # 尝试推送更改
          git push