name: Sync Subscriptions

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:        # 支持手动触发
  
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # 显式授予写入权限
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # 获取完整历史记录
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
          
      - name: Install Dependencies
        run: pnpm install
        working-directory: ${{ github.workspace }}
        
      - name: Create Directories
        run: |
          mkdir -p data
          mkdir -p output
          mkdir -p dist
        
      - name: Build and Run Sync Script
        env:
          LOG_LEVEL: debug
        run: pnpm run build && node dist/sync-subscriptions.js
        
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/ output/
          git commit -m "chore: update subscriptions" || exit 0
          
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}    # 明确指定推送到当前分支